export enum UserRole {
  ADMINISTRATOR = 'ADMINISTRATOR',
  PHYSICIAN = 'PHYSICIAN',
  LABORATORY_USER = 'LABORATORY_USER',
  RECEPTIONIST = 'RECEPTIONIST',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
  UNKNOWN = 'UNKNOWN',
}

export enum AppointmentType {
  GENERAL_CONSULTATION = 'GENERAL_CONSULTATION',
  SPECIALIST_REVIEW = 'SPECIALIST_REVIEW',
  DIAGNOSTIC_FOLLOW_UP = 'DIAGNOSTIC_FOLLOW_UP',
  ROUTINE_CHECKUP = 'ROUTINE_CHECKUP',
}

export enum AppointmentStatus {
  SCHEDULED = 'SCHEDULED',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
}

export enum ConsultationStatus {
  DRAFT = 'DRAFT',
  FINALIZED = 'FINALIZED',
  AMENDED = 'AMENDED',
}

export enum CorrectionReason {
  TYPOGRAPHICAL_ERROR = 'TYPOGRAPHICAL_ERROR',
  DIAGNOSTIC_REVISION = 'DIAGNOSTIC_REVISION',
  SUPPLEMENTARY_INFORMATION = 'SUPPLEMENTARY_INFORMATION',
  MEDICATION_CORRECTION = 'MEDICATION_CORRECTION',
  TRANSCRIPTION_CLARIFICATION = 'TRANSCRIPTION_CLARIFICATION',
}

export enum DiagnosticPriority {
  ROUTINE = 'ROUTINE',
  URGENT = 'URGENT',
  STAT = 'STAT',
}

export enum DiagnosticStatus {
  ORDERED = 'ORDERED',
  COLLECTED = 'COLLECTED',
  IN_ANALYSIS = 'IN_ANALYSIS',
  RESULTED = 'RESULTED',
  VERIFIED = 'VERIFIED',
  REVIEWED = 'REVIEWED',
  CANCELLED = 'CANCELLED',
}

export enum AuditAction {
  USER_AUTHENTICATED = 'USER_AUTHENTICATED',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_SESSION_UNLOCKED = 'USER_SESSION_UNLOCKED',
  UNAUTHORIZED_ACCESS_ATTEMPT = 'UNAUTHORIZED_ACCESS_ATTEMPT',
  USER_ACCESS_REVOKED = 'USER_ACCESS_REVOKED',
  PATIENT_RECORD_CREATED = 'PATIENT_RECORD_CREATED',
  PATIENT_RECORD_VIEWED = 'PATIENT_RECORD_VIEWED',
  PATIENT_RECORD_UPDATED = 'PATIENT_RECORD_UPDATED',
  PATIENT_RECORD_DELETED = 'PATIENT_RECORD_DELETED',
  APPOINTMENT_SCHEDULED = 'APPOINTMENT_SCHEDULED',
  APPOINTMENT_UPDATED = 'APPOINTMENT_UPDATED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  CONSULTATION_CREATED = 'CONSULTATION_CREATED',
  CONSULTATION_FINALIZED = 'CONSULTATION_FINALIZED',
  CONSULTATION_CORRECTION_SUBMITTED = 'CONSULTATION_CORRECTION_SUBMITTED',
  DIAGNOSTIC_ORDER_PLACED = 'DIAGNOSTIC_ORDER_PLACED',
  DIAGNOSTIC_RESULT_SUBMITTED = 'DIAGNOSTIC_RESULT_SUBMITTED',
  DIAGNOSTIC_RESULT_VERIFIED = 'DIAGNOSTIC_RESULT_VERIFIED',
  DIAGNOSTIC_RESULT_REVIEWED = 'DIAGNOSTIC_RESULT_REVIEWED',
}

